# test/generate_fixtures.jl
# Run once to generate test fixture images:
#   julia --project=test test/generate_fixtures.jl
#
# -----------------------------------------------------------------------
# fixtures/v0_1_0_session.toml — DO NOT REGENERATE
# -----------------------------------------------------------------------
# That file is a backward-compatibility fixture: a session file produced by
# the *registered* ImageTally v0.1.0, not by this working tree. It is not
# generated by `generate_fixtures()` above and must never be rewritten by a
# test — the committed bytes are the artifact under test.
#
# It was produced once, in a throwaway environment, with:
#
#   import Pkg
#   Pkg.activate(temp = true)
#   Pkg.add(name = "ImageTally", version = "0.1.0")
#   using ImageTally
#   tags = [Tag("male", :blue, :circle), Tag("female", :red, :utriangle),
#           Tag("juvenile", :green, :diamond)]
#   session = new_session("moths.jpg", 3456, 5184; tags = tags)
#   add_point!(session, 1728.0, 2592.0)
#   add_point!(session, 500.0, 800.0)
#   set_active_tag!(session, "female")
#   add_point!(session, 2000.0, 3000.0)
#   add_point!(session, 3455.0, 5183.0)
#   set_active_tag!(session, "juvenile")
#   add_point!(session, 0.0, 0.0)
#   set_active_tag!(session, "female")
#   set_marker_size!(session, 18.0)
#   save_session(session, "test/fixtures/v0_1_0_session.toml")
#
# Two properties of the file are deliberate and load-bearing:
#
#   * `image_path` is the bare filename "moths.jpg", which does not exist on
#     disk. Real sessions of that era looked like this, and it exercises the
#     "image file missing" branch of the image-size guard in `load_session`.
#   * Key order is unsorted — v0.1.0 called `TOML.print` without
#     `sorted=true`, so order came from `Dict` hash iteration and is not
#     reproducible across Julia versions. Regenerating would lose the record
#     of what the released version actually emitted.
#
# The timestamps are whatever `Dates.now()` returned at generation time.

using FileIO
using ImageIO
using ImageMagick
using Colors
using FixedPointNumbers

function generate_fixtures(dir = joinpath(@__DIR__, "fixtures"))
    mkpath(dir)

    # 64x64 RGB checkerboard — visually distinct, covers all pixel positions
    img_rgb = [
        RGB{N0f8}((i + j) % 2 == 0 ? 0.8 : 0.2, Float32(mod(i * j, 64)) / 64, 0.5) for
        i = 1:64, j = 1:64
    ]

    save(joinpath(dir, "small_rgb.jpg"), img_rgb)
    save(joinpath(dir, "small_rgb.png"), img_rgb)
    save(joinpath(dir, "small_rgb.tif"), img_rgb)
    save(joinpath(dir, "small_rgb.bmp"), img_rgb)

    # 64x64 grayscale 8-bit TIFF — common in microscopy
    img_gray8 = Gray{N0f8}.(img_rgb)
    save(joinpath(dir, "small_gray8.tif"), img_gray8)

    # 64x64 grayscale 16-bit TIFF — common in scientific imaging
    img_gray16 = Gray{N0f16}.(img_rgb)
    save(joinpath(dir, "small_gray16.tif"), img_gray16)

    println("Generated fixtures in $dir:")
    for f in readdir(dir)
        path = joinpath(dir, f)
        println("  $f ($(filesize(path)) bytes)")
    end
end

generate_fixtures()
